application: web-ranks
version: one
runtime: php
api_version: 1

handlers:

- url: /favicon\.ico
  static_files: front/public/favicon.ico
  upload: public/favicon\.ico

- url: /assets/(.*\.(htm$|html$|css$|js$|png$))
  static_files: front/public/assets/\1
  upload: public/assets/(.*\.(htm$|html$|css$|js$|png$))
  application_readable: true

- url: /.*
  script: front/public/index.php
